### ISSUE TITLE
disabled by admin - gives "unexpected state error"

### ISSUE THREAD

**Issue by efef** [eduvpn/macos#136]
As administrator you can disable users in the webportal. I disabled myself, disconnected the VPN and tried to connect. The result was : 
<img width="909" alt="screen shot 2018-09-28 at 16 36 04" src="https://user-images.githubusercontent.com/3393474/46215052-b52ed700-c33c-11e8-9e86-fb9a29fb321d.png">

Second time I got redirect to webpage, which mentions I was disabled (that's good).

**Comment by efef** [comment]
when re-enact this I get another error
<img width="927" alt="screen shot 2018-09-28 at 16 40 53" src="https://user-images.githubusercontent.com/3393474/46215311-5cac0980-c33d-11e8-8856-8d7c48b0955f.png">

**Comment by johankool** [comment]
Could reproduce this by disabling `johan`.

<img width="480" alt="screenshot 2018-10-01 at 11 13 23" src="https://user-images.githubusercontent.com/68731/46280001-0c19f380-c56b-11e8-8e8f-f81b9d0644c9.png">
But when I disabled `fedora_vpn.tuxed.net_johan` it worked as expected.

@fkooman Is the presence of multiple accounts but with prefixes documented somewhere?
