### ISSUE TITLE
remove country VPN profile "distributed mode" 

### ISSUE THREAD

**Issue by efef** [eduvpn/macos#143]
The "distributed" mode means an OAuth token can be used to get a VPN profile/config in other countries. In the app the "-" symbol indicates I should be able to delete a single country, however I can only delete "the netherlands". When I delete .NL all countries disappear.
<img width="507" alt="screen shot 2018-10-09 at 22 56 20" src="https://user-images.githubusercontent.com/3393474/46698329-08473a80-cc17-11e8-8847-160573a7e660.png">
This is not a real bug, but more cosmetic issue.

**Comment by johankool** [comment]
Not sure if this is is really a bug. I though the app should show all providers (aka countries) it can connect too. The text in the error message refers to the fact that you would lose access to other providers/countries too if you remove the one thru which you connected initially.

**Comment by fkooman** [comment]
I think the behavior is actually correct. Maybe you can make it such that only the provider for which you have an access token can be deleted. E.g. if you have a token for "The Netherlands" you can't remove "Denmark", but only "The Netherlands". After which all other "federated" entries would disappear.

**Comment by johankool** [comment]
That is also true already. You can't remove Denmark if you have the token for the Netherlands. The remove button is disabled for Denmark.
