### ISSUE TITLE
/etc/resolv.conf 'gone' after connect on non-WiFi

### ISSUE THREAD

**Issue by efef** [eduvpn/macos#144]
On non-WiFi (e.g. ethernet cable) internet, somehow /etc/resolv.conf is 'gone' after eduVPN connects.

**Comment by jornane** [comment]
Neither `/etc/resolv.conf` nor `/var/run/resolv.conf` are used by macOS; the file is written only as a courtesy to the admin.

Can you send the output of `scutil --dns` when this happens?

**Comment by mkoelewijn** [comment]
It seems that after an hour or so the DNS is working... Here is the `scutil --dns` output when it's not working (so just after I connected):

`DNS configuration

resolver #1
  flags    : Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)

--CUT other resolvers--

DNS configuration (for scoped queries)

resolver #1
  search domain[0] : openvpn
  nameserver[0] : 192.87.106.106
  nameserver[1] : 192.87.36.36
  nameserver[2] : 2001:610:1:800a:192:87:106:106
  nameserver[3] : 2001:610:3:200a:192:87:36:36
  if_index : 9 (utun1)
  flags    : Scoped, Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)`

This is what i get after a hour arso:

`DNS configuration

resolver #1
  search domain[0] : localdomain
  nameserver[0] : 192.168.94.2
  if_index : 7 (en0)
  flags    : Request A records
  reach    : 0x00020002 (Reachable,Directly Reachable Address)

--CUT other resolvers--

DNS configuration (for scoped queries)

resolver #1
  search domain[0] : localdomain
  nameserver[0] : 192.168.94.2
  if_index : 7 (en0)
  flags    : Scoped, Request A records
  reach    : 0x00020002 (Reachable,Directly Reachable Address)`

**Comment by jornane** [comment]
From that output I would expect everything to work fine after connecting. Not really sure how to proceed finding the problem.

**Comment by shaanen** [comment]
Commit #158 does not fix this issue on my MacOS (Mojave) VM with ethernet connection. DNS is not working yet in this case.

**Comment by johankool** [comment]
If I disable WiFi on my MacBook Pro (Mojave) and use Ethernet-USB-C adapter to connect, /etc/resolv.conf remains available.
