### ISSUE TITLE
Sometimes the DNS resolver is reset

### ISSUE THREAD

**Issue by jornane** [eduvpn/macos#147]
Maybe related to #144?

I used eduVPN 1.1 (3) on a train trip, while being connected to the spotty train wifi.
After a seemingly random amount of time, the DNS resolver is reset to the DNS resolver of the local connection. The local resolver is on the same subnet, but lookups fail until the eduVPN client is restarted, or the VPN connection is explicitly disconnected and reconnected by the user.

Sadly, I don't know what triggers the DNS resolver to be reset.

**Comment by jornane** [comment]
It's not just on a public connection, I've just confirmed the same thing happening on my home connection. Just leave VPN on for a couple of minutes, after a while, DNS lookups suddenly time out. Connections directly to IP and existing connections keep working.

**Comment by johankool** [comment]
It seems that Tunnelblick solves this using a lease watch that restores DNS settings when it detects a change. It seems to have at least 2 variants to do this. It seems to me that this would fix this issue, as well as #144. https://github.com/Tunnelblick/Tunnelblick/blob/master/tunnelblick/LeaseWatch.plist and https://github.com/Tunnelblick/Tunnelblick/blob/master/tunnelblick/leasewatch

**Comment by dnmvisser** [comment]
"metoo". Although the interval is not that random, i'm seeing it consistently after 25-30 minutes.

**Comment by jornane** [comment]
Is the version with this fix released? 👍

**Comment by johankool** [comment]
The 1.1 release is coming soon. @efef indicate this issue no longer happened with 1.1b1.
