### ISSUE TITLE
deleting server from list should remove access/refresh token

### ISSUE THREAD

**Issue by fkooman** [eduvpn/macos#148]
When deleting a VPN server entry from the app, the access_token/refresh_token is not deleted, the app should clean up any access_token/refresh_token and certificates (from the keychain) when a server entry is deleted.

**Comment by fkooman** [comment]
Not sure how this currently works for "secure internet". This has to be examined. @mkoelewijn ?

**Comment by fkooman** [comment]
What I mean here is that if you delete a VPN server that's not "local", i.e. where you did not directly obtain the access_token/refresh_token, I guess there only the config/certificate needs to be removed then...

**Comment by mkoelewijn** [comment]
Indeed, nothing seems to be deleted from the keychain when deleting "secure internet" (or any other server)

**Comment by fkooman** [comment]
The access/refresh_tokens is actually more important.
