### ISSUE TITLE
Take Windows "close browser window" HTML/CSS

### ISSUE THREAD

**Issue by fkooman** [eduvpn/macos#153]
```
<!DOCTYPE html>

<html lang="en-US" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" type="text/css" href="/style.css" />
    <title>The client succesfully authorized.</title>
</head>
<body class="finished">
    <table id="wrapper">
    <tr>
        <td>
            <div id="frame">
                <table>
                <tr>
                    <td>
                        <h2>The client succesfully authorized.</h2>
                        <p>You can now close this tab.</p>
                    </td>
                </tr>
                </table>
            </div>
        </td>
    </tr>
    </table>
</body>
</html>
```

https://github.com/Amebis/eduOAuth/blob/master/eduOAuth/Resources/Html/style.css

**Comment by johankool** [comment]
This is defined here: https://github.com/openid/AppAuth-iOS/blob/65ef95c6b38c7889fdda7a22f242fa0156fd43b2/Source/macOS/OIDRedirectHTTPHandler.m#L29

Not trivial to change.

**Comment by fkooman** [comment]
I'd suggest  you send a patch upstream that allows you to configure this page. Or, maybe it is even possible to close the browser window that you opened before? So the message won't stay there for long...

**Comment by johankool** [comment]
Is that html also available on an URL at the eduvpn website somewhere? The easiest, and already supported, option is to redirect the user to another URL.

**Comment by fkooman** [comment]
> Is that html also available on an URL at the eduvpn website somewhere? The easiest, and already supported, option is to redirect the user to another URL.

No. I'd also much rather have it hosted on the local web server you already run anyway... Less interaction with external servers is better!

**Comment by johankool** [comment]
Upstream PR: https://github.com/openid/AppAuth-iOS/pull/413
