### ISSUE TITLE
DNS redundancy fails when 1 of the 2 DNS servers is unavailable

### ISSUE THREAD

**Issue by mkoelewijn** [eduvpn/macos#154]
Yesterday we had an outage on 1 of the 2 DNS servers we use with our eduVPN profile. While Viscosity and the Windows eduVPN app kept on working the OS X did not. It timed out because no DNS servers where responding... (the 192.87.36.36 was unavailable in this example)

####################################
eduVPN MAC OS > does not work!
####################################
resolver #1
*(included my home network)*

resolver #2
  search domain[0] : openvpn
  nameserver[0] : 192.87.106.106
  nameserver[1] : 192.87.36.36
  nameserver[2] : 2001:610:1:800a:192:87:106:106
  nameserver[3] : 2001:610:3:200a:192:87:36:36
  if_index : 18 (utun2)
  flags    : Scoped, Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

####################################
Viscosity OS X / eduvpn > works!
####################################

resolver #1
  search domain[0] : utun10.viscosity
  nameserver[0] : 192.87.106.106
  nameserver[1] : 192.87.36.36
  nameserver[2] : 2001:610:1:800a:192:87:106:106
  nameserver[3] : 2001:610:3:200a:192:87:36:36
  if_index : 18 (utun10)
  flags    : Scoped, Request A records, Request AAAA records
  reach    : 0x00000002 (Reachable)

resolver #2
*(included my home network)*

**Comment by johankool** [comment]
I am afraid I have no idea what happened there or what could cause this.

**Comment by johankool** [comment]
Probably fixed in https://github.com/eduvpn/ios/pull/114 which uses entirely new mechanism to setup VPN connection using Network Extensions. That should also resolve this problem.
