### ISSUE TITLE
Uninstall script does not fully clean install on Mojave

### ISSUE THREAD

**Issue by shaanen** [eduvpn/macos#155]
After I uninstall eduVPN on MacOS Mojave and reinstall it again to start fresh, the custom provider of the previous installation is still there. 

![image](https://user-images.githubusercontent.com/9215678/49232395-200b9580-f3f4-11e8-96de-685b8b367986.png)

The uninstall steps I took:
1. Deleted eduVPN.app under /Applications
2. Ran uninstall.sh
3. Deleted /private/var/folders/*
4. Deleted extra file I found with the find command called "/private/var/db/BootCaches/38F3564C-9389-43A9-AB1C-EF192F214E88/app.org.eduvpn.app.playlist"
4. Reboot

Perhaps the openvpn binary left some files somewhere?

**Comment by johankool** [comment]
Hm... weird... it seems that a backslash was missing in `rm -rf ~/Library/Application Support/eduVPN/`
