### ISSUE TITLE
client doesn't notice wifi disconnect

### ISSUE THREAD

**Issue by efef** [eduvpn/macos#156]
When disabling WiFi interface it takes very long until the client notices the connection is gone.
Maybe you could watch the status of the regular interface or default gateway to determine there is still a 'link' or not.

**Comment by theNerdFromSiliconValley** [comment]
Good Point , I will add that

**Comment by johankool** [comment]
Probably fixed in https://github.com/eduvpn/ios/pull/114 which uses entirely new mechanism to setup VPN connection using Network Extensions. That should also resolve this problem.
