### ISSUE TITLE
DNS fails when using tethering with iPhone

### ISSUE THREAD

**Issue by jornane** [eduvpn/macos#171]
When connecting to the Norwegian instance from a tethered iPhone and Wifi off, DNS lookups don't work anymore through the MacOS apis, but direct to IP connections still work (including manual DNS lookups)

This works:

	% dig myip.tf @158.38.0.1

	; <<>> DiG 9.10.6 <<>> myip.tf @158.38.0.1
	;; global options: +cmd
	;; Got answer:
	;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 38099
	;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

	;; OPT PSEUDOSECTION:
	; EDNS: version: 0, flags:; udp: 4096
	;; QUESTION SECTION:
	;myip.tf.			IN	A

	;; ANSWER SECTION:
	myip.tf.		86400	IN	A	207.148.115.174
	myip.tf.		86400	IN	A	45.77.162.182

	;; Query time: 184 msec
	;; SERVER: 158.38.0.1#53(158.38.0.1)
	;; WHEN: Thu Dec 20 14:20:19 CET 2018
	;; MSG SIZE  rcvd: 68

But this doesnt:

	% host myip.tf
	;; connection timed out; no servers could be reached

The tethered iPhone connection is on en5, while wifi is en0. I recall there being a problem where the client would fail on a cabled connection when Wifi is also connected, but I can't find the relevant issue. They might be related, though.

**Comment by theNerdFromSiliconValley** [comment]
We are working on this issue, It has been fixed for master branch, please wait few days

Just to make sure, can you please check if this following DMG solved your issue

https://drive.google.com/file/d/1GfTQ9HtJxvZZs8GBovCLwWCd49EK0B3q/view?usp=sharing

**Comment by jornane** [comment]
The DMG gives me

	Helper rejected request
	Try reinstalling eduVPN.

Regardless whether I use a tethered connection or a Wifi connection

**Comment by theNerdFromSiliconValley** [comment]
Please uninstall old EduVPN first

**Comment by jornane** [comment]
How do I uninstall eduVPN?

**Comment by theNerdFromSiliconValley** [comment]
Run this script please  https://github.com/eduvpn/macos/blob/master/uninstall.sh

**Comment by jornane** [comment]
It works after removing all files mentioned in the script and rebooting. The upgrading process should be streamlined a bit though. ;)

This solves the issue at hand, great work :)

**Comment by theNerdFromSiliconValley** [comment]
You are welcome, Thanks for your contribution to eduVPN's repo. Please contribute to this repo as much as possible to make the world a better place.
