### ISSUE TITLE
DNS changes are permanent and might not get reverted on disconnect

### ISSUE THREAD

**Issue by jornane** [eduvpn/macos#174]
After my network connection dropped, eduVPN got disconnected.  The client attempts to reconnect, but fails, because the DNS name of the eduVPN server is not in the DNS cache anymore, but the resolver still points to the resolver in the VPN connection.  The OpenVPN process is thus in an endless loop where it cannot lookup the host it should connect to, which it needs to get a working resolver again.

	Fri Dec 21 19:45:59 2018 MANAGEMENT: >STATE:1545417959,RESOLVE,,,,,,
	Fri Dec 21 19:46:29 2018 RESOLVE: Cannot resolve host address: connect.eduvpn.example.com:1194 (nodename nor servname provided, or not known)
	Fri Dec 21 19:46:29 2018 MANAGEMENT: >STATE:1545417989,RESOLVE,,,,,,
	Fri Dec 21 19:46:59 2018 RESOLVE: Cannot resolve host address: connect.eduvpn.example.com:1194 (nodename nor servname provided, or not known)
	Fri Dec 21 19:46:59 2018 Could not determine IPv4/IPv6 protocol
	Fri Dec 21 19:46:59 2018 SIGUSR1[soft,init_instance] received, process restarting
	Fri Dec 21 19:46:59 2018 MANAGEMENT: >STATE:1545418019,RECONNECTING,init_instance,,,,,
	Fri Dec 21 19:46:59 2018 Restart pause, 80 second(s)
	Fri Dec 21 19:48:19 2018 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
	Fri Dec 21 19:48:19 2018 MANAGEMENT: CMD 'certificate'
	Fri Dec 21 19:48:19 2018 Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
	Fri Dec 21 19:48:19 2018 Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
	Fri Dec 21 19:48:19 2018 Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
	Fri Dec 21 19:48:19 2018 Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
	Fri Dec 21 19:48:19 2018 MANAGEMENT: >STATE:1545418099,RESOLVE,,,,,,

The resolver is still pointed to the resolver in the VPN

	DNS configuration (for scoped queries)

	resolver #1
	  search domain[0] : openvpn
	  nameserver[0] : 158.38.0.1
	  nameserver[1] : 158.38.0.2
	  if_index : 14 (en4)
	  flags    : Scoped, Request A records
	  reach    : 0x00000002 (Reachable)

The resolver is also reacable by ping, but it doesn't answer queries outside of the VPN connection.
Even disconnecting eduVPN does not restore the resolver, not even disconnecting the internet connection and reconnecting it helps.

I noticed that suddenly *all* my network connections in MacOS had the VPN DNS settings set manually.  This means that even rebooting will not resolve the problem.  With tethering connections it's even more complicated, because the MacOS UI will not let you change the DNS settings for those.  The only way I got out 

The eduVPN client should not set the VPN resolver when then VPN connection is down, but it should revert all changes that it made earlier.  Ideally, it should not set manual settings for unrelated, disconnected interfaces.  Preferably it should not set any permanent changes for any interface at all.

**Comment by jornane** [comment]
I noticed that even pressing the "Disconnect"-button in eduVPN doesn't clear the DNS settings.

**Comment by johankool** [comment]
Afaik this issue was fixed.
