### ISSUE TITLE
Switch to EdDSA for updates with Sparkle

### ISSUE THREAD

**Issue by fkooman** [eduvpn/macos#197]
Sparkle >= 1.21.0 supports EdDSA (Ed25519) and deprecates DSA. Switch to EdDSA.

**Comment by johankool** [comment]
From the [Sparkle docs](https://sparkle-project.org/documentation/):

> First, run ./bin/generate_keys tool (from the Sparkle distribution root). This needs to be done only once. This tool will do two things: 
> * It will generate a private key and save it in your login Keychain on your Mac. You don’t need to do anything with it, but don’t lose access to your Mac’s Keychain. If you lose it, you may not be able to issue any new updates! 
> * It will print your public key to embed into applications. Copy that key (it’s a base64-encoded string). You can run ./bin/generate_keys again to see your public key at any time.
Add your public key to your app’s Info.plist as a SUPublicEDKey property.

@efef This needs to be done on the Mac building the distributions. Can you do that and provide the public key?

**Comment by efef** [comment]
pubkey OT2lbrvFRXdaWaY0UlrusOgerTXRr53xxcFSZJkmQYQ=
