### ISSUE TITLE
Sparkle doesn't update the app

### ISSUE THREAD

**Issue by efef** [eduvpn/macos#198]
After clean installation, second time the app start it is notifying if you want automatic updates.
<img width="465" alt="screen shot 2019-02-01 at 15 24 10" src="https://user-images.githubusercontent.com/3393474/52135069-4b556f80-2645-11e9-869a-ecb349017702.png">
However if you choose  "check automatically" and restart the app, the app isn't updating. Looking in Preferences "check for updates" doesn't show enabled auto updates.
<img width="503" alt="screen shot 2019-02-01 at 15 24 46" src="https://user-images.githubusercontent.com/3393474/52135219-98d1dc80-2645-11e9-9ae2-a257a0cd56fe.png">
Try turning it on in preferences doesn't work. Restarting app, rebooting MacOS doesn't help either.

**Comment by theNerdFromSiliconValley** [comment]
checking
