### ISSUE TITLE
fix URL for LC

### ISSUE THREAD

**Issue by fkooman** [eduvpn/macos#205]
https://github.com/eduvpn/macos/blob/a955ab01d56050b510f9a9df2cc94302bdbc9579/LetsConnect-Info.plist#L46

https://app.letsconnect-vpn.org/mac/appcast.xml

**Comment by efef** [comment]
fixed in master and latest release
https://github.com/eduvpn/macos/commit/4d22d6b3016c1209ebcb33471058b9994046bc8b#diff-ae675feab035a6a0f06079c36c491db4
https://github.com/eduvpn/macos/commit/4754e8c89b765e020a25cad1a85cd0aa7e265370#diff-ae675feab035a6a0f06079c36c491db4
