### ISSUE TITLE
unknown configuration error 

### ISSUE THREAD

**Issue by fkooman** [eduvpn/macos#210]
![image](https://user-images.githubusercontent.com/616885/53892815-4eb98d80-402d-11e9-88b7-9d0a248ed464.png)

How to debug this?

**Comment by fkooman** [comment]
User tried to reinstall eduVPN app, didn't help.

**Comment by johankool** [comment]
The possible places that this could have happened are in file: https://github.com/eduvpn/macos/blob/master/eduVPN/ConfigurationService.swift Search for ".unknown". A server response with an error other than 401 seems most likely. Though I would expect some error there. The unknown error is only use as fallback.

**Comment by fkooman** [comment]
It would be helpful to actually provide this information to the user, or at least in the log so we can debug this properly. It could be anything now, from a bug in the client to a bug in the server...

**Comment by johankool** [comment]
As I said, this is already a fallback error, so really difficult to tell the user a whole lot more. No data returned or for example a 500 error are the most likely scenarios. It seems unlikely to be a client bug.

**Comment by fkooman** [comment]
Well, logging the full HTTP response, if that is what triggers this error, would be very helpful... :)

I'd consider this kind of unhelpful error message a client bug, no matter if the underlying error is caused by the server.

**Comment by johankool** [comment]
Probably fixed in https://github.com/eduvpn/ios/pull/114 which now uses iOS's mechanism to talk to the API.
