### ISSUE TITLE
DSA to edDSA only migration

### ISSUE THREAD

**Issue by efef** [eduvpn/macos#216]
In both LetsConnect-Info.plist and eduVPN-Info.plist
these string-lines should be removed:

SUPublicDSAKeyFile
dsa_pub.pem

We are signing Sparkle updates with Eddsa key, but due to those strings we also need to use the DSA key. When removed we only need Eddsa key_

**Comment by efef** [comment]
the dsa_pub.pem key can also be removed from the repo

**Comment by johankool** [comment]
Fixed in https://github.com/eduvpn/ios/pull/114 (by removing Sparkle entirely)
