### ISSUE TITLE
Connect to server fails with "Unknown error" after server was upgraded to 2.0

### ISSUE THREAD

**Issue by jornane** [eduvpn/macos#217]
After upgrading our institute server to 2.0, users have been reporting the MacOS app failing with the error "Unknown error". Restarting the app does not solve the problem, but removing the server from the list and then adding it again does help.

The app should detect that the user must log in again, and take the user through that flow.

**Comment by johankool** [comment]
Do you have a screenshot of the error? Or the exact wording of the error and the subtitle, like in [this bug](https://github.com/eduvpn/macos/issues/210). That helps identifying where exactly in the flow the error occurred and more/better error handling is needed.

**Comment by efef** [comment]
I hear the error was shown when using 'institute access'. When installing eduVPN 2.0 server by default a clean install is done. So basically all old oauth tokens & ovpn are invalid. Probably there is an issue when tokens are invalid.

**Comment by johankool** [comment]
From the perspective of the app there isn't much difference at all wether something is 'institute access' or 'secure internet'. It's just in which group they are shown. 

@jornane does mention an URL change. If the base URL of a provider has changed, the fetching of info about the provider in the info.json would fail. I do see that this can trigger an unknown error if the response is something outside the 200-300 range. I'll chang this to a more descriptive error.

**Comment by jornane** [comment]
The base URL was changed, but an updated info.json was still available on the old base URL.

**Comment by jornane** [comment]
<img width="490" alt="Skjermbilde 2019-05-13 kl  15 52 37" src="https://user-images.githubusercontent.com/767872/57628114-944c8680-7599-11e9-8145-92b49ee1529e.png">

**Comment by jornane** [comment]
Restarting the app after that error message appeared did not help.

**Comment by jornane** [comment]
When this happens, the webserver logs show:

	"GET /info.json HTTP/1.1" 200 308 "-" "eduVPN/1.2.1 CFNetwork/978.0.7 Darwin/18.5.0 (x86_64)"
	"GET /portal/api.php/user_info HTTP/1.1" 500 29 "-" "eduVPN/1.2.1 CFNetwork/978.0.7 Darwin/18.5.0 (x86_64)"
	"GET /portal/api.php/profile_list HTTP/1.1" 500 29 "-" "eduVPN/1.2.1 CFNetwork/978.0.7 Darwin/18.5.0 (x86_64)"

Messages show

	portal vpn-user-api: invalid JWT token
	portal vpn-user-api: invalid JWT token

**Comment by johankool** [comment]
Thanks for the follow up @jornane! That 500 seems likely to have been the cause of the unknown error. (The text of this error is improved in the mentioned PR.) @fkooman, shouldn't the API have responded with a 409 or such when the token is invalid?

**Comment by jornane** [comment]
I agree @johankool, error 500 should not cause the client to forget any key material and retry the authentication flow.

The same problem happens now with the upgrade of the secure internet servers.

<img width="480" alt="image" src="https://user-images.githubusercontent.com/767872/57686457-ef35ba80-7639-11e9-868e-410c55332717.png">

I've created an issue for this on the API side.

**Comment by jornane** [comment]
The problem is solved server side now :)
