### ISSUE TITLE
Hide developer mode

### ISSUE THREAD

**Issue by jornane** [eduvpn/macos#222]
One of my users had [trouble with the eduVPN MacOS app](https://github.com/eduvpn/macos/issues/217), and in an misguided attempt to solve the problem himself, he had enabled «Use Developer Mode», which prevented him from retrieving the institution profile.

Developer mode is useful, but it confuses less experienced users. The checkbox should not be as easily available as it is now.

**Comment by jornane** [comment]
I'm thinking that in order to *enable* developer mode, a user must run a `defaults` command. When developer mode is enabled, a banner in the app reminds the user of this, and allows the user through a button to disable developer mode again.

**Comment by johankool** [comment]
Fixed in https://github.com/eduvpn/ios/pull/114
