### ISSUE TITLE
MOTD text is black, even on dark mode

### ISSUE THREAD

**Issue by jornane** [eduvpn/macos#224]
The text should have a light color when using dark mode.

<img width="480" alt="bilde" src="https://user-images.githubusercontent.com/767872/57631880-a251d580-75a0-11e9-9424-c11211832874.png">

Note: sometimes the text is displayed using a light color, but it changes to a dark color when you click on it.

**Comment by johankool** [comment]
Fixed in https://github.com/eduvpn/ios/pull/114
