### ISSUE TITLE
Certificate expired does not trigger reauthenitcation

### ISSUE THREAD

**Issue by mkoelewijn** [eduvpn/macos#225]
When a certificate expire, and on the server side the connection is terminated, the OSX eduVPN connection just terminate and tries to reconnect for at least 10 minutes (even much more than that, got a session now that is trying to reconnect for longer than 25 minutes) while the logging clearly states: WARNING: Your certificate has expired!

In 1 case i got a pop-up box after 10 minutes of reconnecting:

![image](https://user-images.githubusercontent.com/26085443/58170970-2721ab00-7c95-11e9-8c6c-322c0eb0dd31.png)

Ideally the eduVPN client should trigger re-authentication directly if it sees that the certificate is expired.

**Comment by fkooman** [comment]
Earlier occurrences of this issue #183

**Comment by johankool** [comment]
Do I understand it correctly that the certificate expired while the session was active?

**Comment by johankool** [comment]
Fixed with #228
