### ISSUE TITLE
The counters can stop while being connected

### ISSUE THREAD

**Issue by jornane** [eduvpn/macos#226]
After being connected for a while, I took this picture.

<img width="480" alt="image" src="https://user-images.githubusercontent.com/767872/58209377-421d0b00-7ce7-11e9-99ee-2179cf76ce73.png">

Then I uploaded the picture to GitHub, and did some more browsing. A little later, I took a new picture.

<img width="480" alt="image" src="https://user-images.githubusercontent.com/767872/58209796-10f10a80-7ce8-11e9-99b8-0452a201a941.png">

As you can see, the pictures show the same information. All the counters have stopped. The VPN connection still works fine, though.

**Comment by johankool** [comment]
Fixed in https://github.com/eduvpn/ios/pull/114
