### ISSUE TITLE
show in dock  preference doesn't work

### ISSUE THREAD

**Issue by efef** [eduvpn/macos#227]
In the preferences the "show in dock" preference can't be turned off.
When restarting the client this setting is always on

**Comment by efef** [comment]
It seems the app can get in a wrong state when try to disable "show in dock".
Second time I tried this and restarted the app when starting VPN I got this screenshot:

<img width="805" alt="Screenshot 2019-05-23 at 23 19 37" src="https://user-images.githubusercontent.com/3393474/58287575-a5736f80-7db1-11e9-8af7-8a7f54bf6e96.png">

**Comment by efef** [comment]
what is wrong in screenshot:
- the password popup
- color app changed from dark to white

after entering password I get "installation failed"

**Comment by johankool** [comment]
Either "Show in Dock" or "Show in Status Bar" or both must be on. You can't have both off. The UI prevents this situation from happening. Turning off "Show in Dock" hides the window currently. I haven't found a solution for that yet. Choosing "Show eduVPN…" from the status bar brings back the app to the foreground.

I haven't seen the password prompt or the change in color.

**Comment by efef** [comment]
it seems , via spotlight I started a wrong client version, that's why I got a change in color and password prompt. Have deleted those items in this ticket.

**Comment by efef** [comment]
The "show in Dock" issue is, first I turn it off:
<img width="491" alt="Screenshot 2019-05-31 at 10 50 46" src="https://user-images.githubusercontent.com/3393474/58693878-05f64400-8392-11e9-81cc-e7d49df95ae1.png">
Next step: I quit client and restart the app.
I view settings and "show in dock" has been turned-on again.
<img width="490" alt="Screenshot 2019-05-31 at 10 53 23" src="https://user-images.githubusercontent.com/3393474/58694016-5a012880-8392-11e9-9ab4-0acfc3f722ae.png">

**Comment by efef** [comment]
it is impossible to turn it off

**Comment by johankool** [comment]
Fixed in https://github.com/eduvpn/ios/pull/114 (by removing support for this preference entirely)
