### ISSUE TITLE
2FA enrollment - remove

### ISSUE THREAD

**Issue by efef** [eduvpn/macos#239]
Since eduVPN 2.x server, 2FA enrollment will never be triggered because 2FA authentication has been moved to the IdP or Federated authentication layer.
So 2FA enrollment can be removed in the client code.

**Comment by fkooman** [comment]
The code for asking for username/password has to stay I guess for manually imported VPN configurations?

**Comment by johankool** [comment]
Fixed in https://github.com/eduvpn/ios/pull/114
