### ISSUE TITLE
Ed25519 certificates/keys not supported

### ISSUE THREAD

**Issue by fkooman** [eduvpn/macos#240]
As part of my research into [OpenVPN and Modern Crypto](https://www.eduvpn.org/blog/openvpn_modern_crypto.html) I found out that Ed25519 private keys / certificates are not supported by eduVPN for macOS. They *are* supported by Tunnelblick. 

It seems the error is located at the point where the certificate/key are imported in the Keychain. The application gives an error:

> An import error occurred -50

You can test it yourself on https://vpn-dev.tuxed.net/.

**Comment by fkooman** [comment]
I'm using eduVPN 1.2.1 (1.2.1), the latest version from https://app.eduvpn.org/

**Comment by fkooman** [comment]
macOS 10.15

**Comment by johankool** [comment]
Closing this issue and continue with https://github.com/eduvpn/ios/issues/107 which would fix it on both iOS and macOS.
