### ISSUE TITLE
Notarization for macOS >= 10.15 by January 2020?!

### ISSUE THREAD

**Issue by fkooman** [eduvpn/macos#244]
https://developer.apple.com/news/?id=09032019a

From January 2020 this will be required. Not sure if the new iOS/macOS combined app will be ready by then?

**Comment by jornane** [comment]
The new app does not work on 10.14, but I think that the 10.15 is very close to completion now.

**Comment by efef** [comment]
We notarised the 'old' MacOS apps, just to be sure:

Date                      RequestUUID                          Status  Status Code Status Message   
------------------------- ------------------------------------ ------- ----------- ---------------- 
2019-12-02 10:32:20 +0000 XXXX success 0           Package Approved 
2019-11-29 15:19:17 +0000 XXXX success 0           Package Approved
