### ISSUE TITLE
No VPNs available when app is started without internet connection available

### ISSUE THREAD

**Issue by jornane** [eduvpn/macos#48]
It seems that eduVPN requests a lists of available VPNs when it starts, because when I start it without an internet connection, I see this:

![Empty eduVPN window](https://user-images.githubusercontent.com/767872/36951371-4263526e-2003-11e8-867b-856c38d3b5fa.png)

A workaround is to fix the internet connection and restart the app.

I think it would be better if the client caches the list of VPNs, so that it doesn't have to be restarted.

**Comment by fkooman** [comment]
Agreed. Or at the very least show an error...
