### ISSUE TITLE
expired refresh token

### ISSUE THREAD

**Issue by efef** [eduvpn/macos#50]
When refresh token expires or was revoked then a user should re-authenticatie via OAuth.
At this moment the user will get an error message (see screenshot)

<img width="419" alt="screen shot 2018-03-14 at 16 25 14" src="https://user-images.githubusercontent.com/3393474/37412062-8582ebd8-27a4-11e8-9404-8e0ef10dad6f.png">

This can be tested by disabling the authorization in the webinterface.

**Comment by fkooman** [comment]
Some background: expiring refresh tokens are not something that exists in OAuth 2.0 as a concept, but I implemented that for eduVPN/Let's Connect!. However, for the OAuth client itself it does not make any difference as the error handling needs to be exactly the same as when a user would "revoke" the application in the VPN user portal (under Account tab).
