### ISSUE TITLE
make it possible to delete a profile

### ISSUE THREAD

**Issue by fkooman** [eduvpn/macos#64]
Apparently it is only possible to add profiles, and never to delete them. Implement delete. If this was already implemented, my excuses. I don't have the ability to test with macOS.

**Comment by efef** [comment]
via preference it is possible to see the key pairs, but removing them doesn't remove the profile.

**Comment by efef** [comment]
although removal of the key-pair leads to a crash of the app when trying to connect to the removed one.
Also I notice that, when login and adding an additional profile via 'institute access', the new profile isn't shown in the app. I need to restart the app to see the new profile
