### ISSUE TITLE
tray and dock icon always same color

### ISSUE THREAD

**Issue by efef** [eduvpn/macos#65]
Currently the eduVPN icon in tray and in dock have always the same color.
Dock color is orange and in tray it's grey. At least the tray icon color should change depending of the connection status. From red (disconnected), yellow (connecting) to green (connected)

**Comment by johankool** [comment]
The "tray" (status menu) icon actually does already change when connected, though admittedly it is a subtle change. It goes from outline, to filled variant of the icon. It is somewhat customary to avoid using colors in the menubar on macOS.
