### ISSUE TITLE
disabled user gets no message in connect/disconnect screen

### ISSUE THREAD

**Issue by efef** [eduvpn/macos#71]
When an administrator disabled an user. The user gets a notification he's disabled when connecting in the profile-page. When the user is in the "connect/disconnect" page he doesn't get a notification he's disabled.

**Comment by johankool** [comment]
Notifications are shown in the Connect/Disconnect screen. I think that covers this case? <img width="490" alt="screen shot 2018-05-22 at 14 00 02" src="https://user-images.githubusercontent.com/68731/40361115-8fa922da-5dc8-11e8-9641-ad2c05a0c448.png">
