### ISSUE TITLE
developer mode doesn't connect

### ISSUE THREAD

**Issue by efef** [eduvpn/macos#77]
When changed to developer mode (via preferences) it is impossible to connect to an instance.
See screenhost
<img width="440" alt="screen shot 2018-06-04 at 16 48 25" src="https://user-images.githubusercontent.com/3393474/40924326-40a71d6e-6817-11e8-997e-d8720b7f3342.png">

**Comment by johankool** [comment]
This is kinda odd. I always use Developer Mode and haven't seen this error.
