### ISSUE TITLE
delete configuration server side - client doesn't create new configuration

### ISSUE THREAD

**Issue by efef** [eduvpn/macos#78]
test condition:
-running client - VPN is started successfully
-delete server side the available client configuration (...vpn-user-portal/configurations)
-client after a while redirects to authentication page *WRONG*
-clients adds a second server profile  *WRONG*

correct behaviour:
-client should automatically create a new valid configuration (as defined in api.md)

**Comment by fkooman** [comment]
Before connecting you can check if the certificate is gonna work with the "check certificate" call: https://github.com/eduvpn/documentation/blob/master/API.md#check-certificate. The expected behaviour is also explained there.

**Comment by johankool** [comment]
Fixed with https://github.com/eduvpn/macos/pull/90
