### ISSUE TITLE
Delete VPN profile doesn't work correctly

### ISSUE THREAD

**Issue by efef** [eduvpn/macos#79]
Due to issue #78 I have an non working profile.
When deleting the VPN profile, add manual the same server, authenticate and approve the token download. The 'new' profile still can't connect. It looks like as-if the delete wasn't fully done. Server-side there hasn't been created a new config.
Issue might be related to isue #78

**Comment by johankool** [comment]
Seems to be fixed with https://github.com/eduvpn/macos/pull/90
