### ISSUE TITLE
releases | master branch | changelog

### ISSUE THREAD

**Issue by fkooman** [eduvpn/macos#85]
It would be great to have releases and release notes (changelog). This would mean:

- merge all outstanding (dev) branches in master before making a release;
- tag every release that we build and distribute to end users;
- create a changelog showing the difference between the versions;

To create a changelog, you can see the examples in the Windows and Android repositories, i.e. https://github.com/Amebis/eduVPN/blob/master/CHANGES.md and https://github.com/eduvpn/android/blob/master/CHANGES.md

**Comment by fkooman** [comment]
There's no point in doing this for old "releases", but it would be great if this is done from now one, i.e. we have 1.1.3 as a release now. Tag this and then keep a changelog from now on.

**Comment by johankool** [comment]
Agreed. Best approach would be to have @efef ping me when a new release is made so that I can add the appropriate tags. I'll try to add to automate this in the build script eventually.

**Comment by fkooman** [comment]
we still have nothing in master an no release.

**Comment by fkooman** [comment]
Split in 3 separate issues.
